### ISSUE TITLE
Commercial Catches in WA

### ISSUE THREAD

**Issue by shcaba** [shcaba/Sebastes_melanops_WA#10]
Can we get any black rockfish to unknown rockfish composition data for any years?
Can we get what PacFIN uses to allocate black rockfish?

**Comment by shcaba** [comment]
The argument: Trawl-caught Washington landed fish in area 60A may have a better reflection of species comp than using Oregon comps.
What we need from Oregon is the total unknown rockfish catches in 3A before they are allocated to black rockfish and then Washington.

**Comment by nilescbn** [comment]
Just to capture a bit more detail from today's discussion on what Jason was pointing out. The fact that ODFW is using their species comps but more that they're using statewide species comps instead of isolating out samples taken from catch from PacFIN area 3A. Isolating those samples would be idea but it sounds like that's not possible. Theresa is looking at the species comp data we have for the portion of 3A off WA (state catch area code 60A). There could be reasons why Oregon and Washington trawlers fished differently (e.g. different markets) yet the logical thing would be for the species mix to be similar when fishing the same area.

**Comment by nilescbn** [comment]
I've looked at the catches of black rockfish using the WCGOP data for various purposes and I'm thinking it is somewhat relevant to what we're thinking about here. We're talking data from 2002-2019 and so way different than the 1940s of course. Yet it does let us consider how the frequency of encounter changes by latitude.

I looked at it with a generalized additive model (GAM) using set latitude, depth, year, and haul duration. GAMs can capture spatial patterns as they can "wiggle" the best fit lines. The model results are plotted here in terms of predicted probabiliy of catching a black rockfish. It's a binomial model (i.e. 1 for present and 0 for absent).  This is based on location of the start of the tow. The median value for haul duration is just over 2 hours. So they can cover a lot of ground. The data includes tows set 150 fm and shallower (meant to capture fishing shoreward of the RCA). 

Area 3A is delineated with the two, vertical black dotted lines. And the OR/WA boundary is shown with the purple dotted line. You can see that the frequency is highest off WA and in the part coverd by 3A. Tows started just north of the border is the highest peak.  

So looking at this modern day data I do wonder if WA areas would really have a lower percentage of black rockfish than OR. Is there statewide composition percentage inflated by WA areas or the opposite? 

Again, the past could have been different, and targetting is a different thing, yet the hot spots for incidental encounters are in this area we're wondering about.

![black-rock-gam_k100](https://user-images.githubusercontent.com/9826806/218605233-69d7430e-da73-4ed8-9566-47ebdd9c77df.png)

**Comment by nilescbn** [comment]
I forgot to add this earlier but this issue is a perfect example of why ensemble models would be preferable--what the catch was in the 1940s is unknowable. We can make reasonable assumptions, but there are a lot of reasonable assumptions.

While not fully understanding it, I like the approach Ian took with IPHC as to the principle of historical catch reconstruction (and for other reasons). How many years of data go into the model is one of the factors IPHC uses (i.e. long vs short catch history).

**Comment by tsoutt** [comment]
Corey was able to download the species composition table used in PacFIN. I added a tab to look at BLCK percentage in URCK over time for areas 3A and 3B. Here is the link to the file on Google.

https://docs.google.com/spreadsheets/d/1ZkOQiLQsCX5N6mQ0POjLF2h68F57vSv0mdjBmZEfmqg/edit?usp=sharing

**Comment by tsoutt** [comment]
I just uploaded a WDFW standard spp comp into the same folder. These include visual and standard comp samples and were calculated based on current algorithms. No additional borrowing for URCK. No UPOP stuff either.

**Comment by tsoutt** [comment]
![image](https://user-images.githubusercontent.com/117314681/219223362-6de911fe-9ab3-47dc-a7a6-e472e40dfdb5.png)

**Comment by shcaba** [comment]
Thanks for all of this information. I was looking at the provided Google spreadsheet, and trying to summarize these values for 3A across month. 
![image](https://user-images.githubusercontent.com/8162478/219455893-b7f70164-cd23-421f-8990-539a4d718202.png)

![image](https://user-images.githubusercontent.com/8162478/219466148-a59c738b-32aa-4a40-a5ce-7641572fa791.png)

While this is a skewed distribution (not too surprising given the mode is such a low value and the values are bound between 0 and 1), the median is 0.01780. These are just well below the assumed trawl-based black rockfish comps. Having seen all of this, what do folks thing about the assumption we should use for black rockfish from total rockfish catch? Ali will be providing us those historical total unknown rockfish catches from 3A that we can then apply our chosen proportion.
